// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/gogf/gf-demo-user/v2/internal/utils/verification"
)

// Verification 全局验证服务
var Verification = verification.NewVerification()
